<?xml version="1.0" encoding="UTF-8"?>
<tileset name="wilderness" tilewidth="20" tileheight="20" tilecount="320" columns="32">
 <image source="../tiles/combined/wilderness.png" width="640" height="200"/>
 <tile id="0" type="passable"/>
 <tile id="1" type="passable"/>
 <tile id="2" type="passable"/>
 <tile id="3" type="passable"/>
 <tile id="4" type="passable"/>
 <tile id="5" type="impassable"/>
 <tile id="6" type="impassable"/>
 <tile id="7" type="impassable"/>
 <tile id="8" type="impassable"/>
 <tile id="9" type="impassable"/>
 <tile id="10" type="impassable"/>
 <tile id="11" type="impassable"/>
 <tile id="12" type="impassable"/>
 <tile id="13" type="impassable"/>
 <tile id="14" type="impassable"/>
 <tile id="15" type="impassable"/>
 <tile id="16" type="passable"/>
 <tile id="17" type="passable"/>
 <tile id="18" type="passable"/>
 <tile id="19" type="passable"/>
 <tile id="20" type="passable"/>
 <tile id="21" type="passable"/>
 <tile id="22" type="impassable"/>
 <tile id="23" type="impassable"/>
 <tile id="24" type="impassable"/>
 <tile id="25" type="impassable"/>
 <tile id="26" type="impassable"/>
 <tile id="27" type="impassable"/>
 <tile id="28" type="impassable"/>
 <tile id="29" type="impassable"/>
 <tile id="30" type="impassable"/>
 <tile id="31" type="impassable"/>
 <tile id="32" type="passable"/>
 <tile id="33" type="passable"/>
 <tile id="34" type="passable"/>
 <tile id="35" type="passable"/>
 <tile id="36" type="passable"/>
 <tile id="37" type="impassable"/>
 <tile id="38" type="impassable"/>
 <tile id="39" type="impassable"/>
 <tile id="40" type="impassable"/>
 <tile id="41" type="impassable"/>
 <tile id="42" type="impassable"/>
 <tile id="43" type="impassable"/>
 <tile id="44" type="impassable"/>
 <tile id="45" type="impassable"/>
 <tile id="46" type="impassable"/>
 <tile id="47" type="impassable"/>
 <tile id="48" type="passable"/>
 <tile id="49" type="passable"/>
 <tile id="50" type="passable"/>
 <tile id="51" type="passable"/>
 <tile id="52" type="passable"/>
 <tile id="53" type="passable"/>
 <tile id="54" type="impassable"/>
 <tile id="55" type="impassable"/>
 <tile id="56" type="impassable"/>
 <tile id="57" type="impassable"/>
 <tile id="58" type="impassable"/>
 <tile id="59" type="impassable"/>
 <tile id="60" type="impassable"/>
 <tile id="61" type="impassable"/>
 <tile id="62" type="impassable"/>
 <tile id="63" type="impassable"/>
 <tile id="64" type="passable"/>
 <tile id="65" type="passable"/>
 <tile id="66" type="passable"/>
 <tile id="67" type="passable"/>
 <tile id="68" type="passable"/>
 <tile id="69" type="impassable"/>
 <tile id="70" type="impassable"/>
 <tile id="71" type="impassable"/>
 <tile id="72" type="impassable"/>
 <tile id="73" type="impassable"/>
 <tile id="74" type="impassable"/>
 <tile id="75" type="impassable"/>
 <tile id="76" type="impassable"/>
 <tile id="77" type="impassable"/>
 <tile id="78" type="impassable"/>
 <tile id="79" type="impassable"/>
 <tile id="80" type="passable"/>
 <tile id="81" type="passable"/>
 <tile id="82" type="passable"/>
 <tile id="83" type="passable"/>
 <tile id="84" type="passable"/>
 <tile id="85" type="passable"/>
 <tile id="86" type="impassable"/>
 <tile id="87" type="impassable"/>
 <tile id="88" type="impassable"/>
 <tile id="89" type="impassable"/>
 <tile id="90" type="impassable"/>
 <tile id="91" type="impassable"/>
 <tile id="92" type="impassable"/>
 <tile id="93" type="impassable"/>
 <tile id="94" type="impassable"/>
 <tile id="95" type="passable"/>
 <tile id="96" type="passable"/>
 <tile id="97" type="passable"/>
 <tile id="98" type="passable"/>
 <tile id="99" type="passable"/>
 <tile id="100" type="impassable"/>
 <tile id="101" type="impassable"/>
 <tile id="102" type="impassable"/>
 <tile id="103" type="impassable"/>
 <tile id="104" type="impassable"/>
 <tile id="105" type="impassable"/>
 <tile id="106" type="impassable"/>
 <tile id="107" type="impassable"/>
 <tile id="108" type="impassable"/>
 <tile id="109" type="impassable"/>
 <tile id="110" type="impassable"/>
 <tile id="111" type="impassable"/>
 <tile id="112" type="passable"/>
 <tile id="113" type="passable"/>
 <tile id="114" type="passable"/>
 <tile id="115" type="passable"/>
 <tile id="116" type="passable"/>
 <tile id="117" type="passable"/>
 <tile id="118" type="impassable"/>
 <tile id="119" type="impassable"/>
 <tile id="120" type="impassable"/>
 <tile id="121" type="impassable"/>
 <tile id="122" type="impassable"/>
 <tile id="123" type="impassable"/>
 <tile id="124" type="impassable"/>
 <tile id="125" type="passable"/>
 <tile id="126" type="passable"/>
 <tile id="127" type="passable"/>
 <tile id="128" type="passable"/>
 <tile id="129" type="passable"/>
 <tile id="130" type="passable"/>
 <tile id="131" type="passable"/>
 <tile id="132" type="impassable"/>
 <tile id="133" type="impassable"/>
 <tile id="134" type="impassable"/>
 <tile id="135" type="impassable"/>
 <tile id="136" type="impassable"/>
 <tile id="137" type="impassable"/>
 <tile id="138" type="impassable"/>
 <tile id="139" type="impassable"/>
 <tile id="140" type="impassable"/>
 <tile id="141" type="impassable"/>
 <tile id="142" type="impassable"/>
 <tile id="143" type="impassable"/>
 <tile id="144" type="passable"/>
 <tile id="145" type="passable"/>
 <tile id="146" type="passable"/>
 <tile id="147" type="passable"/>
 <tile id="148" type="passable"/>
 <tile id="149" type="passable"/>
 <tile id="150" type="impassable"/>
 <tile id="151" type="impassable"/>
 <tile id="152" type="impassable"/>
 <tile id="153" type="impassable"/>
 <tile id="154" type="impassable"/>
 <tile id="155" type="impassable"/>
 <tile id="156" type="impassable"/>
 <tile id="157" type="passable"/>
 <tile id="158" type="passable"/>
 <tile id="159" type="passable"/>
 <tile id="160" type="passable"/>
 <tile id="161" type="passable"/>
 <tile id="162" type="passable"/>
 <tile id="163" type="passable"/>
 <tile id="164" type="impassable"/>
 <tile id="165" type="impassable"/>
 <tile id="166" type="passable"/>
 <tile id="167" type="impassable"/>
 <tile id="168" type="impassable"/>
 <tile id="169" type="impassable"/>
 <tile id="170" type="impassable"/>
 <tile id="171" type="impassable"/>
 <tile id="172" type="impassable"/>
 <tile id="173" type="impassable"/>
 <tile id="174" type="impassable"/>
 <tile id="175" type="impassable"/>
 <tile id="176" type="passable"/>
 <tile id="177" type="passable"/>
 <tile id="178" type="passable"/>
 <tile id="179" type="passable"/>
 <tile id="180" type="passable"/>
 <tile id="181" type="passable"/>
 <tile id="182" type="impassable"/>
 <tile id="183" type="impassable"/>
 <tile id="184" type="impassable"/>
 <tile id="185" type="impassable"/>
 <tile id="186" type="impassable"/>
 <tile id="187" type="impassable"/>
 <tile id="188" type="impassable"/>
 <tile id="189" type="passable"/>
 <tile id="190" type="passable"/>
 <tile id="191" type="passable"/>
 <tile id="192" type="impassable"/>
 <tile id="193" type="impassable"/>
 <tile id="194" type="impassable"/>
 <tile id="195" type="impassable"/>
 <tile id="196" type="impassable"/>
 <tile id="197" type="impassable"/>
 <tile id="198" type="impassable"/>
 <tile id="199" type="passable"/>
 <tile id="200" type="impassable"/>
 <tile id="201" type="impassable"/>
 <tile id="202" type="impassable"/>
 <tile id="203" type="impassable"/>
 <tile id="204" type="passable"/>
 <tile id="205" type="passable"/>
 <tile id="206" type="passable"/>
 <tile id="207" type="passable"/>
 <tile id="208" type="passable"/>
 <tile id="209" type="passable"/>
 <tile id="210" type="impassable"/>
 <tile id="211" type="impassable"/>
 <tile id="212" type="impassable"/>
 <tile id="213" type="impassable"/>
 <tile id="214" type="impassable"/>
 <tile id="215" type="impassable"/>
 <tile id="216" type="impassable"/>
 <tile id="217" type="impassable"/>
 <tile id="218" type="passable"/>
 <tile id="219" type="passable"/>
 <tile id="220" type="passable"/>
 <tile id="221" type="passable"/>
 <tile id="222" type="passable"/>
 <tile id="223" type="passable"/>
 <tile id="224" type="impassable"/>
 <tile id="225" type="impassable"/>
 <tile id="226" type="impassable"/>
 <tile id="227" type="impassable"/>
 <tile id="228" type="impassable"/>
 <tile id="229" type="impassable"/>
 <tile id="230" type="passable"/>
 <tile id="231" type="passable"/>
 <tile id="232" type="impassable"/>
 <tile id="233" type="impassable"/>
 <tile id="234" type="impassable"/>
 <tile id="236" type="passable"/>
 <tile id="237" type="passable"/>
 <tile id="238" type="impassable"/>
 <tile id="239" type="passable"/>
 <tile id="240" type="passable"/>
 <tile id="241" type="passable"/>
 <tile id="242" type="impassable"/>
 <tile id="243" type="impassable"/>
 <tile id="244" type="impassable"/>
 <tile id="245" type="impassable"/>
 <tile id="246" type="impassable"/>
 <tile id="247" type="impassable"/>
 <tile id="248" type="impassable"/>
 <tile id="249" type="impassable"/>
 <tile id="250" type="passable"/>
 <tile id="251" type="impassable"/>
 <tile id="252" type="passable"/>
 <tile id="253" type="passable"/>
 <tile id="254" type="impassable"/>
 <tile id="255" type="passable"/>
 <tile id="256" type="impassable"/>
 <tile id="257" type="impassable"/>
 <tile id="258" type="impassable"/>
 <tile id="259" type="impassable"/>
 <tile id="260" type="impassable"/>
 <tile id="261" type="impassable"/>
 <tile id="262" type="passable"/>
 <tile id="263" type="passable"/>
 <tile id="264" type="passable"/>
 <tile id="265" type="passable"/>
 <tile id="266" type="passable"/>
 <tile id="267" type="impassable"/>
 <tile id="268" type="passable"/>
 <tile id="272" type="passable"/>
 <tile id="273" type="passable"/>
 <tile id="274" type="impassable"/>
 <tile id="275" type="impassable"/>
 <tile id="276" type="impassable"/>
 <tile id="277" type="impassable"/>
 <tile id="278" type="impassable"/>
 <tile id="279" type="impassable"/>
 <tile id="281" type="passable"/>
 <tile id="288" type="impassable"/>
 <tile id="289" type="impassable"/>
 <tile id="290" type="impassable"/>
 <tile id="291" type="impassable"/>
 <tile id="292" type="impassable"/>
 <tile id="293" type="impassable"/>
 <tile id="294" type="passable"/>
 <tile id="295" type="passable"/>
 <tile id="296" type="passable"/>
 <tile id="297" type="passable"/>
 <tile id="298" type="passable"/>
 <tile id="299" type="passable"/>
 <tile id="300" type="passable"/>
 <tile id="304" type="impassable"/>
 <tile id="305" type="impassable"/>
 <tile id="306" type="impassable"/>
 <tile id="307" type="impassable"/>
 <tile id="308" type="impassable"/>
 <tile id="309" type="impassable"/>
 <tile id="310" type="impassable"/>
 <tile id="311" type="impassable"/>
 <tile id="313" type="passable"/>
</tileset>
